import "./globals.css";
import { Dela_Gothic_One, Poppins } from "next/font/google";

const DeldaGothicOne = Dela_Gothic_One({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={DeldaGothicOne.className}>{children}</body>
    </html>
  );
}
